controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_cam_controller:
      type: velocity_controllers/JointGroupVelocityController

joint_cam_controller:
  ros__parameters:
    joints:
      - camera_joint